apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx # Pod Labels
  ports:
    - name: name-of-the-port
      port: 8081 # service listens on 8081 port
      targetPort: 80 # sevice forwards the request to target 80 (nginx)
      nodePort: 30000 # nodePort ranges from 30000 - 32767
# Service is a abstractino for the set of pods, if we want to communicate with pods
# we have to communicate with associated service because pods ip are efimeral in nature
# Using label service will identify the pods to which the request needs to be tranffered

