apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    COURSE: "Devops"
    Trainer: "Sivakumar Reddy"
spec:
  containers:
    - name: hello-pod
      image: nginx
      ports:
        - containerPort: 80
