apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
    - name: env-demo-container
      image: nginx
      env:
        - name: DEMOGREETING
          value: "Hello from the environment"
        - name: DEMOFAREWELL
          value: "Such a sweet sorrow"
