apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: csecret-pod
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
            name: devops-secret
